// Generated by Wrangler

import { CounterDO } from "./worker/CounterDO";

// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	ASSETS: Fetcher;
	COUNTER: CounterDO
}
